services:
  postgres:
    image: postgres:18
    restart: always
    env_file:
      - .env
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    restart: always
    env_file: 
      - .env
    depends_on: 
      - postgres
    ports:
      - '8000:8000'

volumes:
  pg_data: